name: run main.py action

on:
  schedule:
    - cron: "*/1 * * * *" # every minute

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository content
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'

        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run main.py
          env:
            SOME_SECRET: ${{ secrets.SOME_SECRET }}
          run: python main.py

        - name: commit file
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

        - name: push changes
          uses: ad-m/github-push-action@v0.6.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: master

